all:
  hosts:
    client1:
      ansible_host: 192.168.56.11
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/client1_key
    client2:
      ansible_host: 192.168.56.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/.ssh/client2_key
  children:
    db_servers:
      hosts:
        client1:
    app_servers:
      hosts:
        client2:
