---
- name: Ensure EPEL repository is enabled on RHEL 7/8/9
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install required packages
  ansible.builtin.package:
    name: "{{ packages_list }}"
    state: present
