name: test01
region: us-east-1
#instance_profile_name: EC2StandardRole
instance_type: t3.medium
subnet_id: subnet-0753d677674eaf1ee
ami_id: ami-00ca32bbc84273381
subnet_id: subnet-0753d677674eaf1ee
security_group_ids: [sg-0e5494065f47b9fb0]
key_name: my-key-01
root_device_name: /dev/xvda
root_block_device:
  delete_on_termination: true
  volume_type: gp3
  volume_size: 10
  encrypted: false
ebs_block_device:
  xvdbb:
    delete_on_termination: true
    volume_type: gp3
    volume_size: 5
    encrypted: false
tags:
  team: "coreinfra & dba"
  application: "mpr"
  function: "database"