sysctl_params:
  - name: net.ipv6.conf.all.disable_ipv6
    value: 1
    category: ipv6
  - name: net.ipv6.conf.default.disable_ipv6
    value: 1
    category: ipv6
  - name: kernel.msgmnb
    value: 65536
    category: msg
  - name: kernel.sem
    value: "250 32000 100 128"
    category: sem
  - name: kernel.shmmni
    value: 4096
    category: sem
  - name: kernel.shmmax
    value: 152259518463
    category: sem
  - name: kernel.shmall
    value: 4294967296
    category: sem
  - name: fs.file-max
    value: 6815744
    category: file
  - name: net.ipv4.ip_local_port_range
    value: "9000 65500"
    category: net
  - name: net.core.rmem_default
    value: 262144
    category: net
  - name: net.core.wmem_default
    value: 262144
    category: net
  - name: net.core.rmem_max
    value: 4194304
    category: net
  - name: net.core.wmem_max
    value: 1048576
    category: net
  - name: fs.aio-max-nr
    value: 1048576
    category: io
  - name: vm.nr_hugepages
    value: 24000
    category: hugepages
